### ISSUE TITLE
Create frontend web page

### ISSUE THREAD

**Issue by gksoriginals** [tinkerhub-org/donation-page#2]
Create frontend webpage with this [design](https://www.dropbox.com/s/sjq7ejyeclxvv5q/Donation%20Page.xd?dl=0)![Uploading 79040069...]()

![image](https://user-images.githubusercontent.com/16781355/79040081-b0223780-7c03-11ea-8d5e-d9d5afcbec08.jpeg)

**Comment by gksoriginals** [comment]
For generating TinkerHub logo for the project please use the [campus logo generator](https://tinkerhub-org.github.io/campus-logo-generator/). Type Foundation and download the logo!

**Comment by rabeehrz** [comment]
Does the web-page needs to be responsive? Or will the desktop designs be used in mobiles as well?

**Comment by gksoriginals** [comment]
@rabeehrz responsive would be better.

**Comment by rabeehrz** [comment]
Is there a design? Or work with the desktop one?

**Comment by gksoriginals** [comment]
@ekuttan what’s your thought about this ?

**Comment by gksoriginals** [comment]
> Is there a design? Or work with the desktop one?

@rabeehrz let’s go with the desktop designs as of now. Once a new design is up let’s change to it.

**Comment by vighneshwho** [comment]
@rabeehrz are you currently working on it ?

**Comment by rabeehrz** [comment]
@aka8921 Yeah, but not exclusively. You can submit a PR if you want. I don’t mind at all. I’ll be working on it too anyway.

**Comment by gksoriginals** [comment]
Nice. Or maybe you guys could collaborate! @rabeehrz @aka8921.

**Comment by gksoriginals** [comment]
When the user click donate button after selecting the payment-type and amount frontend should send the details as a json file to the flask app like this. 

`{
     “payment_type” : “one_time”,
      “amount” : <amount>
}
`

Checkout the backend code for getting an idea of its logic.

**Comment by gksoriginals** [comment]
#16 closed this issue. Thanks to @GameGodS3 and @abhijithneilabraham!
