### ISSUE TITLE
Create a thankyou.html and failed.html

### ISSUE THREAD

**Issue by gksoriginals** [tinkerhub-org/donation-page#25]
Create two more pages similar to the index.html design template for

* thankyou.html  : when payment is success
* failed.html : when payment is failed. 

Put this in backend/templates.

**Comment by gksoriginals** [comment]
@GameGodS3 പണി വരുന്നൊണ്ട് അവറാച്ചാ!

**Comment by GameGodS3** [comment]
😂. Ok. On it

**Comment by monkeyscript** [comment]
#55
