### ISSUE TITLE
Make the code reusable

### ISSUE THREAD

**Issue by gksoriginals** [tinkerhub-org/donation-page#32]
So that other people and organisations can use this for implementing payment integration in their website by updating logo, payment methods and credentials.

**Comment by gksoriginals** [comment]
#33 did the following,
- Separated razorpay api calls to payment.py
- Separated routes, app configuration and script for running.
- Created config.py and moved credentials loading to there.

Next we need to separate the payload generation and make it general in payment.py

**Comment by sprajosh** [comment]
One way to achieve this is to create a config file. It will look something like this
`{"org_name": "Tinkerhub", ....}`

Then we need a document which can explain what things to change in the config file - or this can be a bash script
